#!/bin/bash

(crontab -l 2>/dev/null; echo "@reboot /home/$USER/.irc_startup.sh") | crontab -

echo "IRC screen will be automatically started if the server reboots !"
echo -e "Read more about \x1b[1mcrontab\x1b[0m to change this."
