#!/bin/sh

{% set tinc = pillar['tinc'][grains['id']] %}

{{ tinc.get('pre-down',"") }}

{%- if tinc['bridge'] is defined %}
brctl delif {{ tinc['bridge'] }} $INTERFACE
{%- endif %}
ifconfig $INTERFACE down

{{ tinc.get('pre-up',"") }}



