#!/bin/sh
{% if grains['id'] != "azog" %}

ifconfig $INTERFACE {{ pillar['tinc'][grains['id']]['private_ip'] }} netmask 255.255.255.0

{% else %}

brctl addif lan $INTERFACE
ifconfig $INTERFACE up

{% endif %}
