#!/bin/sh

{%- set tinc = pillar['tinc'][grains['id']] %}
############
# Pre down #
############

{{ tinc.get('pre-down',"") }}

########
# Down #
########

{% if tinc['bridge'] is defined %}
brctl delif {{ tinc['bridge'] }} $INTERFACE
{%- endif %}
ifconfig $INTERFACE down

#############
# Post down #
#############

{{ tinc.get('pre-up',"") }}
